# **Obtención y preparación de datos**
# OD04. Operaciones con Array

In [1]:
import numpy as np

## <font color='blue'>**Ordenar y agregar elementos a una matriz**</font>

Ordenar un elemento es simple con `np.sort()`. Puede especificar el eje, el tipo y el orden cuando llama a la función.

In [2]:
arr = np.array([2, 1, 5, 10, 3, 7, 4, 9, 6, 8])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a.shape

(4,)

Para agregar elementos, se utiliza la función `np.concatenate()`:

In [4]:
c = np.concatenate((a, b))
print(c.shape)
c

(8,)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [6]:
print(x)
print()
print(y)
print()
np.concatenate((x, y), axis=0)

[[1 2]
 [3 4]]

[[5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

## <font color='blue'>**Forma y Tamaño de una matriz**</font>

`ndarray.ndim` entrega el número de ejes, o dimensiones, de la matriz.

`ndarray.size` entrega el número total de elementos de la matriz.

`ndarray.shape` entrega una tupla de números enteros que indican el número de elementos almacenados a lo largo de cada dimensión de la matriz. Si, por ejemplo, tiene una matriz 2D con 2 filas y 3 columnas, la forma de su matriz es (2, 3).

Por ejemplo:

In [7]:
arr_ejemplo = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                        [[0, 1, 2, 3],[4, 5, 6, 7]],
                        [[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [8]:
arr_ejemplo.ndim

3

In [9]:
arr_ejemplo.size

24

In [10]:
arr_ejemplo.shape

(3, 2, 4)

## <font color='blue'>**Redimensionamiento de matrices**</font>

El método de `reshape()` le dará una nueva forma a una matriz sin cambiar los datos. Recuerde que cuando usa el método de redimensionamiento, la matriz que desea generar debe tener la misma cantidad de elementos que la matriz original. Si comienza con una matriz con 12 elementos, deberá asegurarse de que su nueva matriz también tenga un total de 12 elementos.

In [11]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [12]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


## <font color='blue'>**Transponer una matriz**</font>

In [13]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

## <font color='blue'>**¿Cómo agregar nuevos ejes (dimensiones) a una matriz?**</font>

Con las funcionaes `np.newaxis` y `np.expand_dims` se puede aumentar las dimensiones de su matriz existente.

El uso de `np.newaxis` aumentará las dimensiones de su matriz en una dimensión cuando se use una vez. Esto significa que una matriz 1D se convertirá en una matriz 2D, una matriz 2D se convertirá en una matriz 3D, y así sucesivamente. Por ejemplo:

In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [16]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[1 2 3 4 5 6 7]]


(1, 7)

Es posible convertir explícitamente una matriz 1D a un vector de fila o a un vector de columna usando `np.newaxis`. Por ejemplo, puede convertir una matriz 1D en un vector de fila insertando un eje a lo largo de la primera dimensión:

In [17]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6 7]]


(1, 7)

o convertirlo en un vector columna, insertando un eje en la segunda dimensión:

In [18]:
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


(7, 1)

También es posible expandir una matriz insertando un nuevo eje en una posición específica con la función `np.expand_dims()`:

In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [20]:
b = np.expand_dims(a, axis=1)
print(b.shape)
b

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
c = np.expand_dims(a, axis=0)
print(c.shape)
c

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

## <font color='blue'>**Elementos únicos y conteo**</font>

In [22]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
valores_unicos = np.unique(a)
print(valores_unicos)

[11 12 13 14 15 16 17 18 19 20]


Para obtener los índices de los valores únicos en una matriz NumPy se debe usar el argumento `return_index` en la función `np.unique()`:

In [23]:
valores_unicos, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


Puede pasar el argumento `return_counts` en `np.unique()` junto con su matriz para obtener el recuento de frecuencia de valores únicos en una matriz de NumPy:

In [24]:
valores_unicos, contar_ocurrencia = np.unique(a, return_counts=True)
print(contar_ocurrencia)

[3 2 2 2 1 1 1 1 1 1]


## <font color='blue'>**Aplicar una función sobre una fila o columna de una matriz**</font>

La función `np.apply_along_axis()` permite aplicar una función sobre una de las dimisiones de un matriz. Por lo que es una herramienta con muchas posibilidades. La función tiene tres parámetros, en el primero se indica la función que se desea aplicar, en la segunda el eje sobre el que se desea aplicar la función y finalmente la matriz. Obteniéndose como salida de la función una matriz con un eje menos que el original.

Por ejemplo:

In [25]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)
np.apply_along_axis(sum, 0, arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [26]:
# Función que calcula el promedio entre el primero y el último elemento de un vector
def my_func(a):
    return (a[0] + a[-1]) * 0.5

b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)
np.apply_along_axis(my_func, 0, b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [27]:
np.apply_along_axis(my_func, 1, b)

array([2., 5., 8.])

### <font color='green'>Actividad 1</font>

Crear un matriz bidimensional _A_ de 5x5 con todos los valores cero. Usando el indexado de matrices, asignar 1 a todos los elementos de la última fila y 5 a todos los elementos de la primera columna. Finalmente, asignar el valor 100 a todos los elementos de la submatriz central de 3x3 de la matriz de 5x5.


In [28]:
# Tu código aquí ...
# Crear un matriz bidimensional A de 5x5 con todos los valores cero. Usando el
# indexado de matrices, asignar 1 a todos los elementos de la última fila y 5
# a todos los elementos de la primera columna. Finalmente, asignar el valor 100
# a todos los elementos de la submatriz central de 3x3 de la matriz de 5x5.


A = np.zeros([5,5])
A[-1,:] = 1
A[:,0] = 5
A[1:4,1:4] = 100
A

array([[  5.,   0.,   0.,   0.,   0.],
       [  5., 100., 100., 100.,   0.],
       [  5., 100., 100., 100.,   0.],
       [  5., 100., 100., 100.,   0.],
       [  5.,   1.,   1.,   1.,   1.]])

<font color='green'>Fin actividad 1</font>

### <font color='green'>Actividad 2</font>

Los diámetros de las esporas del _lycopodium_ pueden medirse por métodos interferométricos &#129299; &#129299; &#129299;. Los resultados de uno de estos experimentos son los siguientes:

<img src='https://drive.google.com/uc?export=view&id=1te4LaaTF_WzyjPShqDOMnP9qDiswwZGG' width="600" align="center" style="margin-right: 50px">

donde $k$ = 5880.

Calcular, usando funciones de NumPy, el diámetro medio de las esporas y la desviación estándar de la muestra. Separar, en matrices independientes, las medidas de los diámetros:

* Que tengan valores inferiores a la media ($\mu$) menos la desviación estándar ($\sigma$), es decir $d < \mu_{d} - \sigma_{d}$
* Que tengan valores superiores a la media más la desviación estándar, es decir $d > \mu_{d} + \sigma_{d}$
* Que tengan valores entre $\mu_{d} - \sigma_{d} < d < \mu_{d} + \sigma_{d}$

*Fuente: Adaptado de Curso de Computación Científica, J. Pérez, T. Roca y C. López*

In [29]:
# Tu código aquí ...
# ingresan los datos de diametro y frecuencia de muestreo y se expanden los datos
k = 5880
diametro = np.arange(14,24)
frecuencia = np.array([1,1,8,24,48,58,35,16,8,1])
data = np.repeat(diametro,frecuencia)

print('Considerando la constante K fuera del análisis')
# se calcula promedio y desviación estandar
mu = np.mean(data)
ds = np.std(data)
print(f'Diámetro promedio {chr(956)} = {mu}/{k} (cm)')
print(f'Desviación estandar {chr(963)} = {round(ds,2)}/{k} (cm)')
print()

# se separan en matrices independientes según lo pedido
data1 = np.array(data[data < mu-ds])
data2 = np.array(data[mu+ds < data])
data3 = np.array(data[(mu-ds < data) & (data < mu+ds)])

print(f'Datos menores a {chr(956)}-{chr(963)}/{k} (cm)')
print(data1)
print()
print(f'Datos mayores a {chr(956)}+{chr(963)}/{k} (cm)')
print(data2)
print()
print(f'Datos entre {chr(956)}-{chr(963)} y {chr(956)}+{chr(963)}/{k} (cm)')
print(data3)
print('\n\n')

print('Considerando la constante K')
# se calcula promedio y desviación estandar
dataK = np.repeat(diametro/k,frecuencia)
muK = np.mean(dataK)
dsK = np.std(dataK)
print(f'Diámetro promedio {chr(956)} = {round(muK,5)} (cm)')
print(f'Desviación estandar {chr(963)} = {round(dsK,5)} (cm)')
print()

# se separan en matrices independientes según lo pedido
data1K = np.array(dataK[dataK < muK-dsK])
data2K = np.array(dataK[muK+dsK < dataK])
data3K = np.array(dataK[(muK-dsK < dataK) & (dataK < muK+dsK)])

print(f'Datos menores a {chr(956)}-{chr(963)} (cm)')
print(data1K)
print()
print(f'Datos mayores a {chr(956)}+{chr(963)} (cm)')
print(data2K)
print()
print(f'Datos entre {chr(956)}-{chr(963)} y {chr(956)}+{chr(963)} (cm)')
print(data3K)

Considerando la constante K fuera del análisis
Diámetro promedio μ = 18.83/5880 (cm)
Desviación estandar σ = 1.48/5880 (cm)

Datos menores a μ-σ/5880 (cm)
[14 15 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17 17 17 17 17 17 17
 17 17 17 17 17 17 17 17 17 17]

Datos mayores a μ+σ/5880 (cm)
[21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 22 22 22 22 22 22 22 22
 23]

Datos entre μ-σ y μ+σ/5880 (cm)
[18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19
 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20]



Considerando la constante K
Diámetro promedio μ = 0.0032 (cm)
Desviación estandar σ = 0.00025 (cm)

Datos menores a μ-σ (cm)
[0.00238095 0.00255102 0.00272109 0.0027

<font color='green'>Fin actividad 2</font>